# This file is generated by Anlogic Timing Wizard. 20 05 2020

#Created Clock
create_clock -name mainclk -period 10 -waveform {0 5} [get_nets {mainclk}]
create_clock -name GCLKIN -period 20 -waveform {0 10} [get_ports {GCLK}]

