/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Projects/FPGA/PVS464/Anlogic/PVS432-SoC/al_ip/BRAM32K_16.v
 ** Date	:	2020 05 19
 ** TD version	:	4.6.14756
\************************************************************/

`timescale 1ns / 1ps

module BRAM32K_16 ( 
	doa, dia, addra, cea, clka, wea,
	dob, dib, addrb, ceb, clkb, web
);

	output [15:0] doa;
	output [15:0] dob;


	input  [15:0] dia;
	input  [15:0] dib;
	input  [11:0] addra;
	input  [11:0] addrb;
	input  [1:0] wea;
	input  [1:0] web;
	input  cea;
	input  ceb;
	input  clka;
	input  clkb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(16),
				.DATA_WIDTH_B(16),
				.ADDR_WIDTH_A(12),
				.ADDR_WIDTH_B(12),
				.DATA_DEPTH_A(4096),
				.DATA_DEPTH_B(4096),
				.BYTE_ENABLE(8),
				.BYTE_A(2),
				.BYTE_B(2),
				.MODE("DP"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("32K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib(dib),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(ceb),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b0),
				.bea(wea),
				.web(1'b0),
				.beb(web),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob(dob));


endmodule