/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Projects/FPGA/PVS464/Anlogic/PVS432-SoC/al_ip/LVDS_DDRTX.v
 ** Date	:	2020 04 26
 ** TD version	:	4.6.14756
\************************************************************/

`timescale 1ns / 1ps

module LVDS_DDRTX ( q, clk, d1, d0, rst );
output 		q;
input  		clk;
input  		d1;
input  		d0;
input  		rst;

		EG_LOGIC_ODDR #(
		.ASYNCRST("ENABLE"))
		oddr (
		.q(q),
		.clk(clk),
		.d1(d1),
		.d0(d0),
		.rst(rst));

endmodule