/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Projects/FPGA/PVS464/Anlogic/PVS432-SoC/al_ip/MainPLL.v
 ** Date	:	2020 05 20
 ** TD version	:	4.6.14756
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             50.000Mhz
//	Clock multiplication factor: 24
//	Clock division factor:       5
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 240.000000MHZ	| 0  DEG     
//		C1        	| 60.000000 MHZ	| 0  DEG     
//		C2        	| 48.000000 MHZ	| 0  DEG     
//		C3        	| 120.000000MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module MainPLL(refclk,
		reset,
		stdby,
		dclk,
		dcs,
		dwe,
		di,
		daddr,
		extlock,
		do,
		clk0_out,
		clk1_out,
		clk2_out,
		clk3_out);

	input refclk;
	input reset;
	input stdby;
	input dclk;
	input dcs;
	input dwe;
	input [7:0]	di;
	input [5:0]	daddr;
	output extlock;
	output [7:0]	do;
	output clk0_out;
	output clk1_out;
	output clk2_out;
	output clk3_out;

	wire clk0_buf;

	EG_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	EG_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.DYNCFG("ENABLE"),
		.FIN("50.000"),
		.FEEDBK_MODE("NORMAL"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("ENABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN(0),
		.ICP_CURRENT(9),
		.KVCO(2),
		.LPF_CAPACITOR(2),
		.LPF_RESISTOR(8),
		.REFCLK_DIV(5),
		.FBCLK_DIV(24),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(4),
		.CLKC0_CPHASE(3),
		.CLKC0_FPHASE(0),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(16),
		.CLKC1_CPHASE(15),
		.CLKC1_FPHASE(0),
		.CLKC2_ENABLE("ENABLE"),
		.CLKC2_DIV(20),
		.CLKC2_CPHASE(19),
		.CLKC2_FPHASE(0),
		.CLKC3_ENABLE("ENABLE"),
		.CLKC3_DIV(8),
		.CLKC3_CPHASE(7),
		.CLKC3_FPHASE(0)	)
	pll_inst (.refclk(refclk),
		.reset(reset),
		.stdby(stdby),
		.extlock(extlock),
		.psclk(1'b0),
		.psdown(1'b0),
		.psstep(1'b0),
		.psclksel(3'b000),
		.psdone(open),
		.dclk(dclk),
		.dcs(dcs),
		.dwe(dwe),
		.di(di),
		.daddr(daddr),
		.do(do),
		.fbclk(clk0_out),
		.clkc({open, clk3_out, clk2_out, clk1_out, clk0_buf}));

endmodule
